config/routes.rb
Rails.application.routes.draw do

  root     'appli_pages#home'
  get       'signup'   => 'users#new'
  get       'signin'       => 'users#show'
  get       'login'       => 'sessions#new'
  post     'login'       => 'sessions#create'
  delete  'logout'    => 'sessions#destroy'

  resources :users
  resources :recipes
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(label: :asc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :label, presence: true, length: { maximum: 140 }
  validates :description, presence: true
  validates :element, presence: true
  validates :ingredient, presence: true
  

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user_recipe,   only: [:edit, :update, :destroy]

  def index
    
    if params[:element_url].blank?
      @recipes = Recipe.all
    else
         @recipes = Recipe.where(:element => params[:element_url]).all

    end
  end
  
  def show
    @recipe = Recipe.find(params[:id])
  end
 
  def new
    @recipe = Recipe.new
  end
 
 def create
    @recipe = Recipe.new(recipe_params)   
    @recipe.user_id = session[:user_id] 
    if @recipe.save
      flash[:info] = "Your recipe have been added. Thanks for contributing"
      redirect_to recipes_url
    else
      render 'new'
    end
  end

  def edit
        @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      flash[:success] = "Recipe updated"
      redirect_to @recipe
    else
      render 'edit'
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted"
    redirect_to recipes_url  
  end
  
  private 
  
     def recipe_params
      params.require(:recipe).permit(:label, :element, :description,
                                   :picture, :video, :ingredient)
    end
  
    def exist_recipe
      if Recipe.find(params[:id])
      end
   end 
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe_form.html.erb
<%= form_for(@recipe, html: { multipart: true }) do |f| %>
			  <%= render 'shared/error_messages', object: f.object  %>
  		<div class="col-md-9" id="form-recipe">
   
      		<%= f.label :label %>
      		<%= f.text_field :label,  class: 'form-control' %>

					<%= f.label :element %>
					<%= f.object.element%>
					<% if f.object.element.nil? %>
					 	<%= f.select(:element, options_for_select( [ 'Starter', 'Main', 'Dessert' ]), class: 'form-control' ) %>				
					<% else %>
				 		<%= f.select(:element, options_for_select( [ 'Starter', 'Main', 'Dessert' ], f.object.element || default_value), class: 'form-control' ) %>
 					<% end %>
      		<%= f.label :ingredient%>
      		<%= f.text_field :ingredient, class: 'form-control' %>

   	   		<%= f.label :description %>
      		<%= f.text_field :description, class: 'form-control'%>

						<%= f.label :picture %>
			    	<%= f.file_field :picture  %>
			
      			<%= f.label :video %>
      			<%= f.file_field :video %>

      	<%= f.submit "Save  my recipe", class: "btn btn-primary" %>

      </div>
 <% end %>

app/views/recipes/edit.html.erb
<% provide(:title, "Amend a Recipe") %>

<div class="col-md-9">
			  <%= render "recipes/recipe_form" %>
</div>

app/views/recipes/index.html.erb
<% provide(:title, "Recipe") %>

<div class="container-fluid col-md-9">
	
  	<% @recipes.each_slice(3) do |recipes| %>
  		<div class="row">	
  			<% recipes.each do |recipe| %>
	  			<div class="card col-md-4" style="padding: 10px">
					  <%= image_tag recipe.picture.url if recipe.picture? %>
					  <div class="card-block" style="border: solid; border-width:  1px;border-color: $grey-light">
					    <h4 class="card-title"><%=recipe.label%></h4>
					    <a href="<%=recipe_path(recipe.id)%>" class="btn btn-primary" style="alignment-adjust: center">Detail</a>
					  </div>
					</div>
				<% end %>
				</br>
    </div> 
 
		<% end %>	
</div>




app/views/recipes/new.html.erb
<% provide(:title, "Add a Recipe") %>

<div class="col-md-9">
			  <%= render "recipes/recipe_form" %>
</div>

app/views/recipes/show.html.erb
<% provide(:title, "Recipe") %>
<div class="col-md-9">

				<p><%=@recipe.label%>	</p>
				<p><%=@recipe.element%>	</p>  
				<p><%=@recipe.ingredient%>	</p>  
				<p><%=@recipe.description%>	</p>  
				<span> <%= image_tag @recipe.picture.url if @recipe.picture? %></span>
				<hr>
				<% if  current_user %>
						<% if current_user.admin? || current_user.id == @recipe.user_id %>
		  			<a><%= link_to "edit", edit_recipe_path()  %></a>		
		  			<a><%= link_to "delete", @recipe, method: :delete,
                                  data: { confirm: "You sure?" } %></a>
        	<% end %>                          
        <%end%>  
</div>