config/routes.rb
Rails.application.routes.draw do

  root     'appli_pages#home'
  get       'signup'   => 'users#new'
  get       'signin'       => 'users#show'
  get       'login'       => 'sessions#new'
  post     'login'       => 'sessions#create'
  delete  'logout'    => 'sessions#destroy'

  resources :users
  resources :recipes
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
			<p>Copyright 2016 - www.berrada.net </p>
  </small>
  <nav>
    <ul>
			<a href="mailto:karim@berrada.net"><span class="glyphicon glyphicon-envelope"> </span></a>
			<a href="mailto:karim@berrada.net">karim@berrada.net</a>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-nav">
  <div class="container">
    <%= link_to "Karim Blog", root_path, id: "logo" %>
    <nav class="navbar-light bg-faded">
      <ul class="nav navbar-nav navbar-left ">
        <li ><%= link_to "Home",   root_path %></li>
        <li ><%= link_to "Recipes",   recipes_path %></li>
        <li ><%= link_to "Portfolio",   ""%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
						<li><%= link_to "Users", users_path %></li>
	          <li class="dropdown">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	              Account <b class="caret"></b>
	            </a>
	            <ul class="dropdown-menu">
	              <li><%= link_to "Profile", current_user %></li>
	              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	              <li class="divider"></li>
	              <li>
	                <%= link_to "Log out", logout_path, method: "delete" %>
	              </li>
	            </ul>
	        	</li>     
        	</ul>
				<%else%>	
 					<li><%= link_to "Log in", login_path  %></li>
			 	<%end%> 
			</ul>
    </nav>
</div>
</header>

app/views/layouts/_navbar.html.erb


<%current_uri = request.env['PATH_INFO']%>

<% if current_uri.include?  "recipe" %>

			<div class="list-group">
						<a href="<%=recipes_path%>" class="list-group-item">All</a>
						<a href="<%=recipes_path%>?element_url=Starter" class="list-group-item">Starter</a>
						<a href="<%=recipes_path%>?element_url=Main" class="list-group-item">Main</a>
						<a href="<%=recipes_path%>?element_url=Dessert" class="list-group-item">Dessert</a>
						<% if current_user %>
							<a href="<%=new_recipe_path%>" class="list-group-item">Add Recipe </a>		
						<%end%>
			</div>

<% else %>
	<% if logged_in? %>
		<% if current_uri.include? "user"%>
					<div class="list-group">
								<a href="<%=users_path%>" class="list-group-item"> All Users</a>
								<a href="<%=user_path(current_user)%>" class="list-group-item">Profile Detail</a>
								<a href="<%=edit_user_path(current_user)%>" class="list-group-item">Edit Profile</a>
					</div>
			<% end %>		
	<% else %>
		<div class="col-md-2">
			<p> Sign up small form</p>
		</div>	
	<% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
    <%= render 'layouts/header' %>
    <div class="container">
		  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="row">
      	<div class="col-md-2">
					<%= render 'layouts/navbar' %>
				</div>	
 					<%= yield %>
    	</div>
    	<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>